// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBAPI.Models;

namespace WEBAPI.Migrations
{
    [DbContext(typeof(DelegiranjeContext))]
    [Migration("20210820000113_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WEBAPI.Models.Kolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojUtakmica")
                        .HasColumnType("int")
                        .HasColumnName("BrojUtakmica");

                    b.HasKey("Id");

                    b.ToTable("Kolo");
                });

            modelBuilder.Entity("WEBAPI.Models.SluzbenoLice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ime");

                    b.Property<string>("Mesto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mesto");

                    b.Property<string>("Uloga")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Uloga");

                    b.Property<int?>("UtakmicaID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtakmicaID");

                    b.ToTable("SluzbenoLice");
                });

            modelBuilder.Entity("WEBAPI.Models.Utakmica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Datum")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Datum");

                    b.Property<int?>("KoloId")
                        .HasColumnType("int");

                    b.Property<string>("MestoOdigravanja")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MestoOdigravanja");

                    b.Property<int>("Redosled")
                        .HasColumnType("int")
                        .HasColumnName("Redosled");

                    b.Property<string>("TimA")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TimA");

                    b.Property<string>("TimB")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TimB");

                    b.Property<string>("VremeOdigravanja")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VremeOdigravanja");

                    b.HasKey("ID");

                    b.HasIndex("KoloId");

                    b.ToTable("Utakmica");
                });

            modelBuilder.Entity("WEBAPI.Models.SluzbenoLice", b =>
                {
                    b.HasOne("WEBAPI.Models.Utakmica", "Utakmica")
                        .WithMany("SluzbenaLica")
                        .HasForeignKey("UtakmicaID");

                    b.Navigation("Utakmica");
                });

            modelBuilder.Entity("WEBAPI.Models.Utakmica", b =>
                {
                    b.HasOne("WEBAPI.Models.Kolo", "Kolo")
                        .WithMany("NizUtakmica")
                        .HasForeignKey("KoloId");

                    b.Navigation("Kolo");
                });

            modelBuilder.Entity("WEBAPI.Models.Kolo", b =>
                {
                    b.Navigation("NizUtakmica");
                });

            modelBuilder.Entity("WEBAPI.Models.Utakmica", b =>
                {
                    b.Navigation("SluzbenaLica");
                });
#pragma warning restore 612, 618
        }
    }
}
